name = "kiberone-partnerka"
compatibility_date = "2026-06-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "kiberone-partnerka"
database_id = "01ae48ad-781f-4023-a015-186ac390a943"
